### ISSUE TITLE
Dialect.paginate方法对SQL语句格式的检查问题

### ISSUE THREAD

**Issue by novaeye** [drinkjava2/jDialects#1]
当一个SELECT语句并不是以SELECT为开头时(比如在SELECT关键字前后有换行符)无法通过参数检查.
https://github.com/drinkjava2/jDialects/blob/master/jdialects/src/main/java/com/github/drinkjava2/jdialects/Dialect.java#L267

**Comment by drinkjava2** [comment]
为简单起见，jDialects只支持select开头的SQL。但没有过滤前面的空格、换行及制表符等，确是个Bug，待更正。

**Comment by novaeye** [comment]
感谢回复:-)

org.apache.commons.lang3.StringUtils.strip(String) 应该是可以用来解决这个问题的.

**Comment by drinkjava2** [comment]
为了"不引入任何第三方库"所以不能用StringUtils，用trim()就可以了，实际上已经更新了，只是没来及release和更新说明，DDL和函数部分有很大变化。

**Comment by novaeye** [comment]
ok, tks 👍
