### ISSUE TITLE
unique constraint create error

### ISSUE THREAD

**Issue by Hero-Rambo** [drinkjava2/jDialects#2]
a table can have a unique constraint with more than 1 column . but it will output unique constraint for each column. it should output one constraint with all column which have same constraint name.  and a column can be used by 2 unique constraint too.

**Comment by drinkjava2** [comment]
Oh, I did not notice of this, will fix as below:
tb.column("xxx").unique()  ---> use automatic generated unique constraint name for this column
tb.column("xxx").unique("somename")  ---> use "somename" as the unique constraint name if database supports, if "somename" used by many columns in same table, will create only 1 compound unique constraint with name "somename" includes these columns.  very similar like index.

**Comment by Hero-Rambo** [comment]
OK，good news。
would you update the artifact in maven repository after fix it？

**Comment by drinkjava2** [comment]
Will update maven repository but will take some days because I'm kind of busy now

**Comment by drinkjava2** [comment]
Updated and released.

**Comment by Hero-Rambo** [comment]
ok unique index fixed. but a column can only have one unique constraint？I have checked，a column can have more than one unique constraint。would you like to check it ？

**Comment by drinkjava2** [comment]
Hi Hero-Rambo,
The update allow one column have many unique constraint, see below code:
		Table t2 = new Table("orders");
		t2.column("name2").STRING(20).unique("A");
		t2.column("email2").STRING(20).unique("A", "B", "C"); 
		String[] dropAndCreateDDL = Dialect.H2Dialect.toDropAndCreateDDL( t2); 
result:
...
alter table orders add constraint A unique (name2,email2)
alter table orders add constraint B unique (email2)
alter table orders add constraint C unique (email2)

**Comment by Hero-Rambo** [comment]
OK 
thanks for your job.

I will  check it next week.

**Comment by drinkjava2** [comment]
Forgot to close this issue.
