### ISSUE TITLE
cascade not supported

### ISSUE THREAD

**Issue by Hero-Rambo** [drinkjava2/jDialects#3]
db ddl have cascade feature，would you like to support it？you can check it from ddlutils docs or mysql grammer

**Comment by drinkjava2** [comment]
Hi just saw this issue, will add this feature, but will take few weeks becuase I'm now focus on DbUtils-Pro project.  In fact there are lots features in Dialect base class Hibernate have but I don't fully understand so just ignored these features.

**Comment by Hero-Rambo** [comment]
Maybe we can extend the feature together.

I post issues ,then you fix them ....

**Comment by drinkjava2** [comment]
Good idea, I'm appreciated you like this project and would spend time on finding bug, I'll keep work on this project.

**Comment by drinkjava2** [comment]
Close and reject this issue, I have no time ability to add this feature
